# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergoldgroup',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usergoldgroup',
            name='is_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usergoldgroup',
            name='is_salesman',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usergoldgroup',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
