# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 01:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170131_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergoldgroup',
            name='city_residence',
        ),
    ]
