# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0004_remove_usergoldgroup_city_residence'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoldgroup',
            name='city_residence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locations.City'),
        ),
    ]
