# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usergoldgroup_city_residence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Bank'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Code'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='line_cgv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.LineCgv'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_other',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
